name: emoticoach
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  device_info_plus: ^10.1.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_ui_auth: ^3.0.0
  google_sign_in: ^6.1.6
  epubx: ^4.0.0
  #epub_view: ^3.2.0
  epub_view: ^3.2.0
  path_provider: ^2.1.4

  http: ^1.4.0
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_overlay_window: ^0.5.0
  multiavatar: ^0.1.5
  rename: ^3.0.2
  shimmer: ^3.0.0
  simple_animations: ^5.1.0
  supercharged: ^2.1.1
  iconify_flutter: ^0.0.7
  smooth_page_indicator: ^1.2.1
  #flutter_native_splash: ^2.4.6
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - backend/.env
    - assets/images/
    - assets/icons/
    - assets/epub/
    - assets/sample.json
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
